name: linux-x86_64

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'assets/**'
  workflow_dispatch:

jobs:
  pam_wordle:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ libpam0g-dev cmake

      - name: Compile
        run: |
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make "-j$(nproc)"
